### PR TITLE
Add tab for multi arch in history page

### LINKED ISSUE #130: Can't see all architectures associated with a tag
Just installed the UI. It was super easy with the REGISTRY_URL once I understood what it meant. The ability to put the registry on a private network and have the UI proxy /v2/ so it's all nice and tidy is fantastic.

## Bug description

I'm building multi-platform images using `docker buildx` like this:

     docker buildx build --platform linux/amd64,linux/arm/v7 -t registry/name . --push

That is an all-in-one build/tag/push operation that results in an image I can run on arm64 or Raspberry Pi.

The UI shows the image and the (only) tag ("latest"). If I click history I see the amd64 version. Is there some way to see the arm/v7 version as well?

## How to Reproduce

Use buildx as described to make a multi-platform image, then inspect with UI.

## Expected behavior

Some indication that multiple architectures are supported by the tag. Some way to navigate them?

## System information

- Docker registry UI:
    - Version: v1.4.8
    - Server: docker
    - Docker version: 18.09.8
    - Docker registry ui tag: static
    - OS/Arch: amd64
    - Tools: docker-compose, docker buildx

### PR DESCRIPTION
**Pull request by Joxit**
## Feature

This PR add the support for multi-arch images.

## Screenshoot

multi-arch

@bjj: This style is OK for you ?

closes #130

### CODE REVIEW

**Comment by bjj** [comment]
Looks good. I assume the hardcoded arch list is just to make the mockup?

**Comment by Joxit** [comment]
Yes, this is a mock for the style only, I will continue the PR ASAP :smile:

**Comment by Joxit** [comment]
I added the behaviour for multi arch images. Can you test it ?

**Comment by bjj** [comment]
Last change fixes all of the issues I saw. Tabs appear on first load, and order is stable when flipping tabs. It's much easier to flip between them to see what's changing, and easier to skim down the list to find the relevant history 👍

**Comment by Joxit** [comment]
Yeaaah cool ! :smile: thank you again for your feedback !

**Pull request merged**
