### PR TITLE
Kubernetes support

### PR DESCRIPTION
**Pull request by sebt3**
Added a simple kubernetes example and a helm chart for easy deployments

### CODE REVIEW

**Comment by Joxit** [comment]
Hello, thank you for your contribution :)
Can you add one `README.md` in `examples/helm` and `examples/kubernets` for a basic usage ?

**Comment by sebt3** [comment]
Well my writing is rather subpar. But I can come up with something, hoping you'll get contributions on that doc side ;)

**Comment by sebt3** [comment]
Here you go :)

**Comment by Joxit** [comment]
Ha ha don't worry, I think it will be OK :)
I will trust you because I'm not familiar with k8s and helm :sweat_smile:.

(Peut-être qu'un jour je testerais vos exemples :wink:)

**Comment by Joxit** [comment]
Hi there, I created an official Helm chart for docker-registry-ui available here https://helm.joxit.dev/ with the source code [on github](https://github.com/Joxit/helm-charts). The Chart is compatible with the latest docker registry UI :smile:  (2.2.1)

Feel free to send me feedback if you try it.

**Pull request merged**
